import Image from "next/image";
import Script from "next/script";
import {
  Smartphone,
  Hourglass,
  Puzzle,
  Network,
  Apple,
  Monitor,
  Globe,
  ShieldCheck,
  Database,
  TestTube,
  GitBranch,
  Zap,
  Server,
  Layers,
  Code,
  ArrowRight,
} from "lucide-react";
import Navbar from "./components/Navbar";
import FAQ from "./components/FAQ";
import ROICalculator from "./components/ROICalculator";
import ScrollReveal from "./components/ScrollReveal";
import HeroMockup from "./components/HeroMockup";

const BOOKING_URL = "https://tidycal.com/feranmiicm";

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      name: "Swiftly",
      url: "https://swiftly-website-snowy.vercel.app",
      logo: "https://swiftly-website-snowy.vercel.app/swiftly.png",
      description:
        "AI-native app development agency. We fix vibe-coded apps and build production-ready mobile, web, and desktop software. Live in 6 weeks, guaranteed.",
      sameAs: [],
    },
    {
      "@type": "WebSite",
      name: "Swiftly",
      url: "https://swiftly-website-snowy.vercel.app",
    },
    {
      "@type": "Service",
      name: "App Development & Vibe Code Fixing",
      provider: { "@type": "Organization", name: "Swiftly" },
      description:
        "We fix vibe-coded apps and build production-ready mobile, web, and desktop software. Fixed pricing from $8,500. 6-week delivery guarantee.",
      areaServed: "Worldwide",
      offers: [
        { "@type": "Offer", name: "Starter Plan", price: "8500", priceCurrency: "USD", description: "One platform, up to 8 screens, 6-week delivery" },
        { "@type": "Offer", name: "Growth Plan", price: "14900", priceCurrency: "USD", description: "Both platforms, up to 15 screens, 6-week delivery, backend included" },
      ],
    },
    {
      "@type": "FAQPage",
      mainEntity: [
        { "@type": "Question", name: "How can you really deliver in 6 weeks?", acceptedAnswer: { "@type": "Answer", text: "We achieve this through a fixed process, pre-built component libraries, and a dedicated team on your project only." } },
        { "@type": "Question", name: "What if I need changes after launch?", acceptedAnswer: { "@type": "Answer", text: "Every plan includes post-launch support (30–90 days). After that, we offer flexible maintenance plans — or you take the source code to any developer." } },
        { "@type": "Question", name: "What is vibe-coded software?", acceptedAnswer: { "@type": "Answer", text: "Vibe coding is when you use AI tools like Cursor, Bolt, v0, Lovable, or Replit to generate an app quickly. We take that prototype and make it production-ready." } },
        { "@type": "Question", name: "Can you fix code generated by any AI tool?", acceptedAnswer: { "@type": "Answer", text: "Yes. We work with codebases generated by Cursor, Bolt, v0, Lovable, Replit, ChatGPT, Claude, Copilot, and any other AI coding tool." } },
        { "@type": "Question", name: "Do you build web and desktop apps too?", acceptedAnswer: { "@type": "Answer", text: "We build across all platforms — mobile, web (Next.js, React, Vue, SaaS), and desktop (Electron, Tauri)." } },
        { "@type": "Question", name: "How does the launch guarantee work?", acceptedAnswer: { "@type": "Answer", text: "If your app isn't live within 6 weeks — for reasons within our control — we continue working at no additional charge. Written into every contract." } },
      ],
    },
  ],
};

function StarSVG() {
  return (
    <svg className="star" viewBox="0 0 24 24">
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}

function Stars() {
  return (
    <div className="stars" role="img" aria-label="5 out of 5 stars">
      <StarSVG /><StarSVG /><StarSVG /><StarSVG /><StarSVG />
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Script
        id="json-ld"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <ScrollReveal />
      <Navbar bookingUrl={BOOKING_URL} />

      <main>

      {/* ═══ HERO ═══ */}
      <section className="hero">
        <div className="hero-grid"></div>
        <div className="hero-glow"></div>

        <div className="container hero-content">
          <div className="hero-layout">
            <div>
              <div className="hero-eyebrow">
               
                <span>We fix vibe-coded apps</span>
              </div>

              <h1>
                Your app.
                <br />
                Live in
                <br />
                <em>6 weeks.</em>
                <br />
                Guaranteed.
              </h1>

              <p className="hero-sub">
                Built something with Cursor, Bolt, or v0 that&apos;s not quite ready
                for real users? We take it the rest of the way. Mobile, web, desktop
                &mdash; we ship production code, not prototypes.
              </p>

              <div className="hero-actions">
                <a href={BOOKING_URL} target="_blank" rel="noopener noreferrer" className="btn-primary">
                  Book a Free Call <ArrowRight size={16} />
                </a>
                <a href="#how-it-works" className="btn-ghost">
                  How It Works
                </a>
              </div>

              <div className="hero-stats reveal">
                <div className="hero-stat">
                  <strong>6 Wks</strong>
                  <span>Average delivery</span>
                </div>
                <div className="h-divider"></div>
                <div className="hero-stat">
                  <strong>Any Platform</strong>
                  <span>Mobile, web, desktop</span>
                </div>
                <div className="h-divider"></div>
                <div className="hero-stat">
                  <strong>From $8.5k</strong>
                  <span>Fixed price</span>
                </div>
              </div>
            </div>

            <HeroMockup />
          </div>
        </div>

        <div className="scroll-indicator">
          <span>Scroll</span>
          <div className="scroll-arrow"></div>
        </div>
      </section>

      {/* ═══ THE PROBLEM ═══ */}
      <section className="pain" id="pain">
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">The Problem</div>
            <h2>
              Your prototype works.
              <br />
              Your code <em>doesn&apos;t.</em>
            </h2>
            <p>
              You got the idea out fast with AI. But now it needs to handle
              real users, real payments, and real scale.
            </p>
          </div>

          <div className="pain-grid reveal">
            <div className="pain-card">
              <div className="pain-icon"><Puzzle size={22} /></div>
              <h3>It Works on Your Machine</h3>
              <p>
                Looks great in a demo. But there&apos;s no auth, no error handling,
                and the whole thing falls apart the second a real user touches it.
              </p>
              <span className="pain-stat">Most vibe-coded apps break in production</span>
            </div>
            <div className="pain-card">
              <div className="pain-icon"><Network size={22} /></div>
              <h3>Nobody Wants to Touch the Code</h3>
              <p>
                AI doesn&apos;t plan ahead. You end up with a mess of tangled files
                that no developer wants to inherit or build on top of.
              </p>
              <span className="pain-stat">3x more expensive to fix later</span>
            </div>
            <div className="pain-card">
              <div className="pain-icon"><Hourglass size={22} /></div>
              <h3>Hiring an Agency Takes Months</h3>
              <p>
                Most shops quote 6 months minimum and charge enterprise rates.
                You don&apos;t have that kind of time or budget.
              </p>
              <span className="pain-stat">Avg. 8 months before you see anything</span>
            </div>
          </div>
        </div>
      </section>

      {/* ═══ WHAT WE DO ═══ */}
      <section id="vibe-fix" style={{ padding: "7rem 0" }}>
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">What We Do</div>
            <h2>
              We turn your prototype
              <br />
              into a <em>real product.</em>
            </h2>
            <p>
              Send us what you&apos;ve got. We&apos;ll clean it up, build it out,
              and ship it. Or we can start from scratch if you prefer.
            </p>
          </div>

          <div className="speed-wrap" style={{ marginBottom: "3rem" }}>
            <div className="speed-card us reveal" style={{ textAlign: "left" }}>
              <div className="speed-lbl">We Fix</div>
              <div className="speed-items">
                <div className="speed-item good"><Code size={16} style={{ flexShrink: 0 }} />Messy code → clean architecture</div>
                <div className="speed-item good"><Database size={16} style={{ flexShrink: 0 }} />Add real auth, databases, APIs</div>
                <div className="speed-item good"><TestTube size={16} style={{ flexShrink: 0 }} />Write tests, handle errors properly</div>
                <div className="speed-item good"><GitBranch size={16} style={{ flexShrink: 0 }} />Set up CI/CD so deploys just work</div>
                <div className="speed-item good"><ShieldCheck size={16} style={{ flexShrink: 0 }} />Security review before you go live</div>
              </div>
            </div>
            <div className="speed-card us reveal" style={{ textAlign: "left" }}>
              <div className="speed-lbl">We Build For</div>
              <div className="speed-items">
                <div className="speed-item good"><Smartphone size={16} style={{ flexShrink: 0 }} />Mobile — iOS, Android, React Native, Flutter</div>
                <div className="speed-item good"><Globe size={16} style={{ flexShrink: 0 }} />Web — Next.js, React, Vue, SaaS</div>
                <div className="speed-item good"><Monitor size={16} style={{ flexShrink: 0 }} />Desktop — Electron, Tauri, native</div>
                <div className="speed-item good"><Server size={16} style={{ flexShrink: 0 }} />Backend — Node, Python, Go, databases</div>
                <div className="speed-item good"><Layers size={16} style={{ flexShrink: 0 }} />Full-stack — end-to-end MVP builds</div>
              </div>
            </div>
          </div>

          <div className="services-grid">
            {[
              { icon: <Zap size={28} />, title: "Vibe Code Rescue", desc: "You built it with AI. We make it actually work.", items: ["Full code audit", "Auth, security, error handling", "Tests and CI/CD", "Works with Cursor, Bolt, v0, etc."] },
              { icon: <Apple size={28} />, title: "iOS Apps", desc: "Native apps that get approved and keep users coming back.", items: ["Swift / SwiftUI", "We handle App Store submission", "Push notifications & analytics", "Stripe & Apple Pay"] },
              { icon: <Smartphone size={28} />, title: "Android Apps", desc: "Clean Android apps that pass Google Play review the first time.", items: ["Kotlin / Jetpack Compose", "We handle Play Store submission", "Maps & location services", "Firebase backend"] },
              { icon: <Globe size={28} />, title: "Web Apps", desc: "SaaS tools, dashboards, customer portals. Whatever you need.", items: ["Next.js / React / Vue", "Admin panels & dashboards", "API design & integrations", "Deployed on Vercel, AWS, or GCP"] },
              { icon: <Monitor size={28} />, title: "Desktop Apps", desc: "Desktop software that runs on Mac, Windows, and Linux.", items: ["Electron / Tauri", "Native OS features", "Works offline", "Auto-updates built in"] },
              { icon: <Layers size={28} />, title: "Cross-Platform", desc: "One codebase for both iOS and Android. Ship faster, spend less.", items: ["React Native / Flutter", "Both app stores, one build", "Shared design system", "Best option if budget matters"] },
            ].map((s) => (
              <div className="service-card reveal" key={s.title}>
                <span className="service-icon">{s.icon}</span>
                <h3>{s.title}</h3>
                <p>{s.desc}</p>
                <ul className="service-list">
                  {s.items.map((item) => <li key={item}>{item}</li>)}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══ HOW IT WORKS ═══ */}
      <section id="how-it-works" style={{ padding: "7rem 0", background: "var(--bg2)" }}>
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">How It Works</div>
            <h2>
              Four steps.
              <br />
              <em>Six weeks.</em>
            </h2>
            <p>Simple process, no runaround.</p>
          </div>

          <div className="process-steps">
            {[
              { num: "01", title: "We Talk", desc: "30-minute call. We look at what you have (or what you need), figure out the scope, and give you a fixed price on the spot.", week: "Day 1" },
              { num: "02", title: "Plan & Design", desc: "We map out the architecture, put together wireframes, and get your sign-off before we write any code.", week: "Week 1–2" },
              { num: "03", title: "Build & Show", desc: "You get a working demo every week. You give feedback, we iterate. No waiting months to see something.", week: "Week 2–5" },
              { num: "04", title: "Ship It", desc: "Deployed, tested, docs written. You get the source code, the accounts, everything. It's yours.", week: "Week 6" },
            ].map((step) => (
              <div className="step reveal" key={step.num}>
                <div className="step-num">{step.num}</div>
                <h3>{step.title}</h3>
                <p>{step.desc}</p>
                <span className="step-week">{step.week}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══ US VS THEM ═══ */}
      <section style={{ padding: "7rem 0" }}>
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">Why Us</div>
            <h2>
              Weeks, not months.
            </h2>
            <p>Here&apos;s how we compare to a typical agency.</p>
          </div>

          <div className="speed-wrap">
            <div className="speed-card them reveal">
              <div className="speed-lbl">Traditional Agency</div>
              <div className="speed-time">6–12<br /><span style={{ fontSize: "22px" }}>months</span></div>
              <div className="speed-items">
                <div className="speed-item"><div className="sdot"></div>3–4 weeks just for a proposal</div>
                <div className="speed-item"><div className="sdot"></div>Redesigns that restart the clock</div>
                <div className="speed-item"><div className="sdot"></div>Scope creep and delayed launches</div>
                <div className="speed-item"><div className="sdot"></div>Monthly retainers, unclear output</div>
                <div className="speed-item"><div className="sdot"></div>Developers juggling 10+ projects</div>
              </div>
            </div>
            <div className="speed-card us reveal">
              <div className="speed-lbl">Swiftly</div>
              <div className="speed-time">6<br /><span style={{ fontSize: "22px" }}>weeks</span></div>
              <div className="speed-items">
                <div className="speed-item good"><div className="sdot"></div>You see working code within days</div>
                <div className="speed-item good"><div className="sdot"></div>Weekly demos, not monthly status emails</div>
                <div className="speed-item good"><div className="sdot"></div>Fixed price. No scope creep surprises</div>
                <div className="speed-item good"><div className="sdot"></div>One team, one project, full attention</div>
                <div className="speed-item good"><div className="sdot"></div>Ships on time or we work free until it does</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ═══ SOCIAL PROOF ═══ */}
      <section style={{ padding: "7rem 0", background: "var(--bg2)" }} id="testimonials">
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">From Our Clients</div>
            <h2>Don&apos;t take our word for it.</h2>
            <p>Here&apos;s what people say after working with us.</p>
          </div>

          <div className="testi-grid">
            {[
              { quote: "\u201CWe went from zero mobile presence to a fully live app in 5 weeks. The process was airtight — weekly demos kept us confident the whole way through.\u201D", initials: "SC", name: "Sarah Chen", role: "Owner, Chen HVAC Services", result: "+62% mobile revenue in 60 days" },
              { quote: "\u201CEvery agency quoted 6 months and enterprise prices. Swiftly delivered in 6 weeks at a third of the cost. The app paid for itself in the first month.\u201D", initials: "MJ", name: "Marcus Johnson", role: "Operations Manager, Rapid Retail", result: "ROI achieved in 11 days" },
              { quote: "\u201CI was skeptical about the 6-week claim. They delivered in 5 weeks 3 days. Source code handover was clean, documented, and our dev picked it up immediately.\u201D", initials: "ER", name: "Elena Rodriguez", role: "CEO, Bright Electric Co.", result: "29% customer retention boost" },
            ].map((t) => (
              <div className="testi-card reveal" key={t.initials}>
                <Stars />
                <p className="testi-quote">{t.quote}</p>
                <div className="testi-author">
                  <div className="testi-avatar">{t.initials}</div>
                  <div><h4>{t.name}</h4><p>{t.role}</p></div>
                </div>
                <span className="testi-result">{t.result}</span>
              </div>
            ))}
          </div>

          {/* Trust points inline */}
          <div className="trust-grid" style={{ marginTop: "4rem" }}>
            {[
              { num: "01", title: "We have skin in the game", desc: "We're a small team. Your project is literally our reputation. We can't afford to do bad work." },
              { num: "02", title: "6-week guarantee, in writing", desc: "It's in the contract. If we miss the deadline, we keep working for free until it ships." },
              { num: "03", title: "You talk to the person building it", desc: "No project managers, no account reps. You get weekly demos from the engineer doing the work." },
              { num: "04", title: "You own everything", desc: "Source code, design files, store accounts. All yours from day one. Walk away whenever you want." },
            ].map((card) => (
              <div className="trust-card reveal" key={card.num}>
                <div className="trust-num">{card.num}</div>
                <div><h4>{card.title}</h4><p>{card.desc}</p></div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ═══ PRICING ═══ */}
      <section id="pricing" style={{ padding: "7rem 0" }}>
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">Pricing</div>
            <h2>You know the price<br />before we start.</h2>
            <p>Every plan includes the 6-week guarantee.</p>
          </div>

          {/* Competitor context */}
          <div className="pricing-context reveal">
            <strong>For context:</strong> agencies typically charge $50k–$150k+ for the same work and take 6–12 months. We do it for a fraction of the cost because AI handles the heavy lifting. You pay for the result, not the hours.
          </div>

          <div className="pricing-cards">
            {/* Starter */}
            <div className="pricing-card reveal">
              <div className="pricing-tier">Starter</div>
              <div className="pricing-price"><sup>$</sup>8,500</div>
              <div className="pricing-note">One platform &middot; fixed price</div>
              <div className="pricing-divider"></div>
              <ul className="pricing-features">
                <li className="yes"><span className="chk">✓</span> Pick one: mobile, web, or desktop</li>
                <li className="yes"><span className="chk">✓</span> UI/UX design included</li>
                <li className="yes"><span className="chk">✓</span> Vibe code audit &amp; fix</li>
                <li className="yes"><span className="chk">✓</span> 6-week delivery guarantee</li>
                <li className="yes"><span className="chk">✓</span> 30 days post-launch support</li>
                <li><span style={{ color: "var(--muted)" }}>–</span> Backend / admin panel</li>
              </ul>
              <div className="pricing-compare">Agencies charge <strong>$20k–$50k</strong> for this</div>
              <a href={BOOKING_URL} target="_blank" rel="noopener noreferrer" className="pricing-btn outline">Get Started</a>
            </div>

            {/* Growth */}
            <div className="pricing-card featured reveal">
              <div className="featured-badge">Most Popular</div>
              <div className="pricing-tier">Growth</div>
              <div className="pricing-price"><sup>$</sup>14,900</div>
              <div className="pricing-note">Multi-platform &middot; fixed price</div>
              <div className="pricing-divider"></div>
              <ul className="pricing-features">
                <li className="yes"><span className="chk">✓</span> Up to 2 platforms (mobile + web, etc.)</li>
                <li className="yes"><span className="chk">✓</span> UI/UX design included</li>
                <li className="yes"><span className="chk">✓</span> Full vibe code → production rewrite</li>
                <li className="yes"><span className="chk">✓</span> 6-week delivery guarantee</li>
                <li className="yes"><span className="chk">✓</span> 60 days post-launch support</li>
                <li className="yes"><span className="chk">✓</span> Backend + admin panel</li>
              </ul>
              <div className="pricing-compare featured">Agencies charge <strong>$50k–$120k</strong> for this</div>
              <a href={BOOKING_URL} target="_blank" rel="noopener noreferrer" className="pricing-btn primary">Book Discovery Call</a>
            </div>

            {/* Scale */}
            <div className="pricing-card reveal">
              <div className="pricing-tier">Scale</div>
              <div className="pricing-price">Custom</div>
              <div className="pricing-note">Complex builds &middot; scoped to your needs</div>
              <div className="pricing-divider"></div>
              <ul className="pricing-features">
                <li className="yes"><span className="chk">✓</span> All platforms</li>
                <li className="yes"><span className="chk">✓</span> Full custom UI/UX</li>
                <li className="yes"><span className="chk">✓</span> Complex backend / API work</li>
                <li className="yes"><span className="chk">✓</span> Third-party integrations</li>
                <li className="yes"><span className="chk">✓</span> 90 days post-launch support</li>
                <li className="yes"><span className="chk">✓</span> Ongoing maintenance plan</li>
              </ul>
              <div className="pricing-compare">Agencies charge <strong>$75k–$300k+</strong> for this</div>
              <a href={BOOKING_URL} target="_blank" rel="noopener noreferrer" className="pricing-btn outline">Contact Sales</a>
            </div>
          </div>
        </div>
      </section>

      {/* ═══ ROI CALCULATOR ═══ */}
      <section id="roi" style={{ padding: "7rem 0", background: "var(--bg2)" }}>
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">ROI Calculator</div>
            <h2>Run the numbers<br />yourself.</h2>
            <p>Most of our clients make their money back in the first month.</p>
          </div>
          <ROICalculator bookingUrl={BOOKING_URL} />
        </div>
      </section>

      {/* ═══ FAQ ═══ */}
      <section id="faq" style={{ padding: "7rem 0" }}>
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">FAQ</div>
            <h2>Questions we<br />always get asked.</h2>
          </div>
          <FAQ />
        </div>
      </section>

      {/* ═══ FINAL CTA ═══ */}
      <section id="book" className="cta-banner">
        <div className="container">
          <div className="cta-inner">
            <h2>
              Let&apos;s get your app
              <br />
              <em>out the door.</em>
            </h2>
            <div className="cta-right">
              <a href={BOOKING_URL} target="_blank" rel="noopener noreferrer" className="btn-primary">
                Book Your Free 30-Min Call <ArrowRight size={16} />
              </a>
              <span className="cta-note">
                No commitment. No sales pitch. Just a conversation.
              </span>
            </div>
          </div>
        </div>
      </section>

      </main>

      <footer>
        <div className="container">
          <div className="footer-top">
            <div className="footer-brand">
              <a href="#" className="footer-logo">
                <Image src="/swiftly.png" alt="Swiftly" width={120} height={40} />
              </a>
              <p className="footer-tagline">
                We turn your vision into a polished mobile app &mdash;
                designed, built, and launched in record time.
              </p>
            </div>
            <div className="footer-links">
              <a href="#vibe-fix">Services</a>
              <a href="#how-it-works">Process</a>
              <a href="#pricing">Pricing</a>
              <a href="#roi">ROI</a>
              <a href="#faq">FAQ</a>
            </div>
            <div className="footer-social">
              <a href="https://x.com/SwiftlyShip_" target="_blank" rel="noopener noreferrer" aria-label="X (Twitter)">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg>
              </a>
              <a href="https://instagram.com" target="_blank" rel="noopener noreferrer" aria-label="Instagram">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"/><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"/></svg>
              </a>
              <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433a2.062 2.062 0 0 1-2.063-2.065 2.064 2.064 0 1 1 2.063 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>
              </a>
            </div>
          </div>
          <div className="footer-bottom">
            <span className="footer-copy">&copy; 2026 Swiftly Build Inc. All rights reserved.</span>
          </div>
        </div>
      </footer>

    </>
  );
}
