"use client";

import { useState } from "react";
import Image from "next/image";
import Script from "next/script";
import {
  Smartphone,
  Hourglass,
  DollarSign,
  Puzzle,
  Network,
  Rocket,
  Apple,
  Monitor,
  Globe,
  ShieldCheck,
  Database,
  TestTube,
  GitBranch,
  Zap,
  Server,
  Layers,
  Code,
} from "lucide-react";
import Navbar from "./components/Navbar";
import ContactModal from "./components/ContactModal";
import FAQ from "./components/FAQ";
import ROICalculator from "./components/ROICalculator";
import ScrollReveal from "./components/ScrollReveal";

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      name: "Swiftly",
      url: "https://swiftly-website-snowy.vercel.app",
      logo: "https://swiftly-website-snowy.vercel.app/logo.png",
      description:
        "AI-native app development agency. We fix vibe-coded apps and build production-ready mobile, web, and desktop software. Live in 6 weeks, guaranteed.",
      sameAs: [],
    },
    {
      "@type": "WebSite",
      name: "Swiftly",
      url: "https://swiftly-website-snowy.vercel.app",
    },
    {
      "@type": "Service",
      name: "App Development & Vibe Code Fixing",
      provider: {
        "@type": "Organization",
        name: "Swiftly",
      },
      description:
        "We fix vibe-coded apps and build production-ready mobile, web, and desktop software. Fixed pricing from $8,500. 6-week delivery guarantee.",
      areaServed: "Worldwide",
      offers: [
        {
          "@type": "Offer",
          name: "Starter Plan",
          price: "8500",
          priceCurrency: "USD",
          description:
            "One platform, up to 8 screens, 6-week delivery",
        },
        {
          "@type": "Offer",
          name: "Growth Plan",
          price: "14900",
          priceCurrency: "USD",
          description:
            "Both platforms, up to 15 screens, 6-week delivery, backend included",
        },
      ],
    },
    {
      "@type": "FAQPage",
      mainEntity: [
        {
          "@type": "Question",
          name: "How can you really deliver in 6 weeks?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "We achieve this through a fixed process, pre-built component libraries, and a dedicated team on your project only. We don't start a project unless we have the bandwidth to complete it on schedule.",
          },
        },
        {
          "@type": "Question",
          name: "What if I need changes after launch?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Every plan includes post-launch support (30-90 days depending on tier). After that, we offer flexible maintenance plans — or you take the source code to any developer. You're never locked in.",
          },
        },
        {
          "@type": "Question",
          name: "Do I need a technical background to work with you?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Not at all. Most clients are business owners, not developers. Our weekly demos are designed to be reviewed by non-technical stakeholders.",
          },
        },
        {
          "@type": "Question",
          name: "What happens on the free discovery call?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "A 30-minute conversation where we learn about your business and what you want the app to accomplish. By the end you'll have a clear scope, timeline, and whether we're the right fit — no pitch, no pressure.",
          },
        },
        {
          "@type": "Question",
          name: "How does the launch guarantee work?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "If your app isn't live within 6 weeks of the agreed kickoff — for reasons within our control — we continue working at no additional charge. Written into every contract, not just a verbal promise.",
          },
        },
        {
          "@type": "Question",
          name: "Can you integrate with my existing tools?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes — we integrate with Salesforce, HubSpot, Stripe, QuickBooks, Xero, and custom APIs. Mention your tools in the discovery call and we'll scope it in.",
          },
        },
        {
          "@type": "Question",
          name: "What is vibe-coded software?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Vibe coding is when you use AI tools like Cursor, Bolt, v0, Lovable, or Replit to generate an app quickly. The result usually works as a demo but lacks the architecture, security, error handling, and testing needed for real users. We take that prototype and make it production-ready.",
          },
        },
        {
          "@type": "Question",
          name: "Can you fix code generated by any AI tool?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes. We work with codebases generated by Cursor, Bolt, v0, Lovable, Replit, ChatGPT, Claude, Copilot, and any other AI coding tool. We also fix hand-written prototypes that need the same production hardening.",
          },
        },
        {
          "@type": "Question",
          name: "Do you build web and desktop apps too, or just mobile?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "We build across all platforms — mobile (iOS, Android, cross-platform), web (Next.js, React, Vue, SaaS), and desktop (Electron, Tauri). We also take existing vibe-coded apps on any platform and bring them to production quality.",
          },
        },
      ],
    },
  ],
};

function StarSVG() {
  return (
    <svg className="star" viewBox="0 0 24 24">
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}

function Stars() {
  return (
    <div className="stars" role="img" aria-label="5 out of 5 stars">
      <StarSVG />
      <StarSVG />
      <StarSVG />
      <StarSVG />
      <StarSVG />
    </div>
  );
}

export default function Home() {
  const [modalOpen, setModalOpen] = useState(false);
  const openModal = () => setModalOpen(true);
  const closeModal = () => setModalOpen(false);

  return (
    <>
      <Script
        id="json-ld"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <ScrollReveal />
      <Navbar onOpenModal={openModal} />

      <main>
      {/* HERO */}
      <section className="hero">
        <div className="hero-grid"></div>
        <div className="hero-glow"></div>

        <div className="container hero-content">
          <div className="hero-layout">
            <div>
              <div className="hero-eyebrow">
                <div className="hero-eyebrow-line"></div>
                <span>Mobile App Development for SMBs</span>
              </div>

              <h1>
                Your app.
                <br />
                Live in
                <br />
                <em>6 weeks.</em>
                <br />
                Guaranteed.
              </h1>

              <p className="hero-sub">
                We build iOS and Android apps for growing businesses — faster
                than any agency, without the enterprise price tag or 6-month
                wait.
              </p>

              <div className="hero-actions">
                <a href="#roi" className="btn-primary">
                  Calculate Your ROI &rarr;
                </a>
                <a href="#process" className="btn-ghost">
                  See How It Works
                </a>
              </div>

              <div className="hero-stats reveal">
                <div className="hero-stat">
                  <strong>6 Wks</strong>
                  <span>Average delivery</span>
                </div>
                <div className="h-divider"></div>
                <div className="hero-stat">
                  <strong>iOS + Android</strong>
                  <span>Both platforms</span>
                </div>
                <div className="h-divider"></div>
                <div className="hero-stat">
                  <strong>Free</strong>
                  <span>Discovery call</span>
                </div>
              </div>
            </div>

            {/* App Mockup */}
            <div className="app-mockup-wrap reveal">
              <div className="app-mockup">
                <div className="app-mockup-inner">
                  <div className="app-header">
                    <div>
                      <h3>Today&apos;s Dashboard</h3>
                      <p>8 jobs completed</p>
                    </div>
                    <span className="badge-green">+23% this week</span>
                  </div>

                  <div className="job-row done">
                    <div>
                      <h4>HVAC Repair — Johnson St</h4>
                      <p>2:00 PM – 3:30 PM</p>
                    </div>
                    <span className="job-status done">Done</span>
                  </div>
                  <div className="job-row active">
                    <div>
                      <h4>App Build — Retail Client</h4>
                      <p>4:00 PM – 6:00 PM</p>
                    </div>
                    <span className="job-status active">In Progress</span>
                  </div>
                  <div className="job-row enroute">
                    <div>
                      <h4>Go-Live — Downtown Caf&eacute;</h4>
                      <p>6:30 PM – 7:30 PM</p>
                    </div>
                    <span className="job-status enroute">En Route</span>
                  </div>

                  <div className="app-footer">
                    <span>Revenue Today</span>
                    <strong>$4,250</strong>
                  </div>
                </div>
              </div>

              {/* Floating stat cards */}
              <div className="float-card fc-left">
                <div className="float-card-icon">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <polyline points="23 6 13.5 15.5 8.5 10.5 1 18" />
                    <polyline points="17 6 23 6 23 12" />
                  </svg>
                </div>
                <div>
                  <p>Efficiency Gain</p>
                  <strong>+40%</strong>
                </div>
              </div>
              <div className="float-card fc-right">
                <div className="float-card-icon">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <circle cx="12" cy="12" r="10" />
                    <polyline points="12 6 12 12 16 14" />
                  </svg>
                </div>
                <div>
                  <p>Time Saved / Day</p>
                  <strong>5.2 hrs</strong>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="scroll-indicator">
          <span>Scroll</span>
          <div className="scroll-arrow"></div>
        </div>
      </section>

      {/* PAIN POINTS */}
      <section className="pain" id="pain">
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">The Problem</div>
            <h2>
              Your competitors
              <br />
              already have an app.
            </h2>
            <p>
              Every day without a mobile presence is customers going to someone
              else. Here&apos;s what it&apos;s costing you.
            </p>
          </div>

          <div className="pain-grid reveal">
            <div className="pain-card">
              <div className="pain-icon"><Smartphone size={22} /></div>
              <h3>Invisible to Mobile Users</h3>
              <p>
                Over 70% of web traffic is mobile. No app means you&apos;re
                missing the majority of your market every single day.
              </p>
              <span className="pain-stat">Affects 7 in 10 visitors</span>
            </div>
            <div className="pain-card">
              <div className="pain-icon"><Hourglass size={22} /></div>
              <h3>Agencies Take Forever</h3>
              <p>
                Traditional agencies quote 6–12 months. By the time you launch,
                the window of opportunity has closed.
              </p>
              <span className="pain-stat">Avg. 8 months wasted</span>
            </div>
            <div className="pain-card">
              <div className="pain-icon"><DollarSign size={22} /></div>
              <h3>Enterprise Pricing for SMBs</h3>
              <p>
                Most agencies were built for big budgets. You end up paying for
                overhead and layers you never needed.
              </p>
              <span className="pain-stat">3× overpayment on average</span>
            </div>
          </div>
        </div>
      </section>

      {/* VIBE CODE FIX */}
      <section id="vibe-fix" style={{ padding: "7rem 0" }}>
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">Vibe Coded? We Fix That.</div>
            <h2>
              You built it with AI.
              <br />
              We make it <em>production-ready.</em>
            </h2>
            <p>
              Cursor, Bolt, v0, Lovable, Replit — great for prototypes, dangerous for production.
              We take your vibe-coded app and turn it into real software.
            </p>
          </div>

          <div className="pain-grid reveal">
            <div className="pain-card">
              <div className="pain-icon"><Puzzle size={22} /></div>
              <h3>Works on Demo Day, Breaks in Prod</h3>
              <p>
                AI-generated code looks right but crumbles under real users.
                No error handling, no edge cases, no security — just vibes.
              </p>
              <span className="pain-stat">90% of vibe-coded apps fail at scale</span>
            </div>
            <div className="pain-card">
              <div className="pain-icon"><Network size={22} /></div>
              <h3>Spaghetti Architecture</h3>
              <p>
                AI doesn&apos;t think about structure. You end up with tangled dependencies,
                no separation of concerns, and code no engineer wants to touch.
              </p>
              <span className="pain-stat">Avg. 3x refactor cost if left unchecked</span>
            </div>
            <div className="pain-card">
              <div className="pain-icon"><Rocket size={22} /></div>
              <h3>Stuck Between Prototype &amp; Product</h3>
              <p>
                You&apos;ve proven the idea works. Now you need real auth, real databases,
                real deployment, real testing — and AI can&apos;t close that gap alone.
              </p>
              <span className="pain-stat">The &quot;last 20%&quot; takes 80% of the time</span>
            </div>
          </div>

          <div className="vibe-fix-cta reveal" style={{ marginTop: "3rem", textAlign: "center" }}>
            <h3 style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: "clamp(22px, 3vw, 30px)", letterSpacing: "-.02em", marginBottom: "1rem" }}>
              We take your vibe-coded prototype and deliver
            </h3>
            <div className="speed-wrap" style={{ marginTop: "1.5rem" }}>
              <div className="speed-card us reveal" style={{ textAlign: "left" }}>
                <div className="speed-lbl">What You Get</div>
                <div className="speed-items">
                  <div className="speed-item good"><Code size={16} style={{ flexShrink: 0 }} />Production-grade architecture &amp; clean code</div>
                  <div className="speed-item good"><Database size={16} style={{ flexShrink: 0 }} />Real auth, databases, API integrations</div>
                  <div className="speed-item good"><TestTube size={16} style={{ flexShrink: 0 }} />Error handling, testing &amp; monitoring</div>
                  <div className="speed-item good"><GitBranch size={16} style={{ flexShrink: 0 }} />CI/CD pipeline &amp; deployment setup</div>
                  <div className="speed-item good"><ShieldCheck size={16} style={{ flexShrink: 0 }} />Security audit &amp; performance optimization</div>
                </div>
              </div>
              <div className="speed-card them reveal" style={{ textAlign: "left" }}>
                <div className="speed-lbl">Platforms We Fix</div>
                <div className="speed-items">
                  <div className="speed-item good"><Smartphone size={16} style={{ flexShrink: 0 }} />Mobile — iOS, Android, React Native, Flutter</div>
                  <div className="speed-item good"><Globe size={16} style={{ flexShrink: 0 }} />Web — Next.js, React, Vue, SaaS dashboards</div>
                  <div className="speed-item good"><Monitor size={16} style={{ flexShrink: 0 }} />Desktop — Electron, Tauri, native apps</div>
                  <div className="speed-item good"><Server size={16} style={{ flexShrink: 0 }} />Backend — Node, Python, Go, databases</div>
                  <div className="speed-item good"><Layers size={16} style={{ flexShrink: 0 }} />Full-stack — end-to-end MVP builds</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ROI CALCULATOR */}
      <section id="roi" style={{ padding: "7rem 0" }}>
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">ROI Calculator</div>
            <h2>
              See what your app
              <br />
              is worth to your business.
            </h2>
            <p>
              Most SMBs see payback within the first month. Slide to your
              numbers and see the impact.
            </p>
          </div>

          <ROICalculator onOpenModal={openModal} />
        </div>
      </section>

      {/* PROCESS */}
      <section
        id="process"
        style={{ padding: "7rem 0", background: "var(--bg2)" }}
      >
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">Our Process</div>
            <h2>
              From idea to live app
              <br />
              in four fast steps.
            </h2>
            <p>
              We&apos;ve eliminated every bottleneck in the traditional agency
              model.
            </p>
          </div>

          <div className="process-steps">
            {[
              {
                num: "01",
                title: "Discovery Call",
                desc: "We map your business goals, users, and must-have features. No jargon, just clarity.",
                week: "Day 1",
              },
              {
                num: "02",
                title: "Design Sprint",
                desc: "Full wireframes and a clickable prototype you can test with real customers before a single line of code.",
                week: "Week 1–2",
              },
              {
                num: "03",
                title: "Build & Review",
                desc: "Weekly demos so you see progress, give feedback, and stay in control. No surprises.",
                week: "Week 2–5",
              },
              {
                num: "04",
                title: "Launch & Handover",
                desc: "App Store and Google Play approved, source code delivered, team trained. You own everything.",
                week: "Week 6",
              },
            ].map((step) => (
              <div className="step reveal" key={step.num}>
                <div className="step-num">{step.num}</div>
                <h3>{step.title}</h3>
                <p>{step.desc}</p>
                <span className="step-week">{step.week}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* SPEED COMPARISON */}
      <section style={{ padding: "7rem 0" }}>
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">Speed Is Our Product</div>
            <h2>
              We ship in weeks.
              <br />
              Not months.
            </h2>
            <p>Speed is built into our process, not bolted on.</p>
          </div>

          <div className="speed-wrap">
            <div className="speed-card them reveal">
              <div className="speed-lbl">Typical Agency</div>
              <div className="speed-time">
                6–12
                <br />
                <span style={{ fontSize: "22px" }}>months</span>
              </div>
              <div className="speed-items">
                <div className="speed-item">
                  <div className="sdot"></div>3–4 weeks just for a proposal
                </div>
                <div className="speed-item">
                  <div className="sdot"></div>Redesigns that restart the clock
                </div>
                <div className="speed-item">
                  <div className="sdot"></div>Scope creep and delayed launches
                </div>
                <div className="speed-item">
                  <div className="sdot"></div>Monthly retainers with unclear
                  output
                </div>
                <div className="speed-item">
                  <div className="sdot"></div>Developers juggling 10+ projects
                </div>
              </div>
            </div>

            <div className="speed-card us reveal">
              <div className="speed-lbl">Swiftly</div>
              <div className="speed-time">
                6<br />
                <span style={{ fontSize: "22px" }}>weeks</span>
              </div>
              <div className="speed-items">
                <div className="speed-item good">
                  <div className="sdot"></div>Discovery call to prototype in 2
                  weeks
                </div>
                <div className="speed-item good">
                  <div className="sdot"></div>Weekly milestones you can see and
                  test
                </div>
                <div className="speed-item good">
                  <div className="sdot"></div>Fixed scope, fixed timeline, fixed
                  price
                </div>
                <div className="speed-item good">
                  <div className="sdot"></div>Dedicated team on your project only
                </div>
                <div className="speed-item good">
                  <div className="sdot"></div>Launch guarantee or you don&apos;t
                  pay
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* SERVICES */}
      <section
        id="services"
        style={{ padding: "7rem 0", background: "var(--bg2)" }}
      >
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">What We Build</div>
            <h2>
              Every app your
              <br />
              business might need.
            </h2>
            <p>Practical, revenue-generating apps — not flashy tech demos.</p>
          </div>

          <div className="services-grid">
            <div className="service-card reveal">
              <span className="service-icon"><Apple size={28} /></span>
              <h3>iOS App Development</h3>
              <p>Native iPhone and iPad apps built for performance, App Store approval, and real customer engagement.</p>
              <ul className="service-list">
                <li>Swift / SwiftUI</li>
                <li>App Store submission included</li>
                <li>Push notifications &amp; analytics</li>
                <li>Stripe &amp; Apple Pay integration</li>
              </ul>
            </div>
            <div className="service-card reveal">
              <span className="service-icon"><Smartphone size={28} /></span>
              <h3>Android App Development</h3>
              <p>Polished Android apps that work across all major devices and pass Google Play review first time.</p>
              <ul className="service-list">
                <li>Kotlin / Jetpack Compose</li>
                <li>Google Play submission included</li>
                <li>Maps &amp; location services</li>
                <li>Firebase backend integration</li>
              </ul>
            </div>
            <div className="service-card reveal">
              <span className="service-icon"><Globe size={28} /></span>
              <h3>Web App Development</h3>
              <p>Fast, responsive web apps and SaaS dashboards built with modern frameworks. Deploy anywhere.</p>
              <ul className="service-list">
                <li>Next.js / React / Vue</li>
                <li>SaaS dashboards &amp; admin panels</li>
                <li>API design &amp; integrations</li>
                <li>Vercel / AWS / GCP deployment</li>
              </ul>
            </div>
            <div className="service-card reveal">
              <span className="service-icon"><Monitor size={28} /></span>
              <h3>Desktop App Development</h3>
              <p>Cross-platform desktop apps that run on macOS, Windows, and Linux with native performance.</p>
              <ul className="service-list">
                <li>Electron / Tauri</li>
                <li>Native OS integrations</li>
                <li>Offline-first architecture</li>
                <li>Auto-update &amp; distribution</li>
              </ul>
            </div>
            <div className="service-card reveal">
              <span className="service-icon"><Layers size={28} /></span>
              <h3>Cross-Platform Mobile</h3>
              <p>One codebase, two platforms. Launch on iOS and Android simultaneously at a fraction of the usual cost.</p>
              <ul className="service-list">
                <li>React Native / Flutter</li>
                <li>Both stores, one build cycle</li>
                <li>Shared design system</li>
                <li>Best value for SMB budgets</li>
              </ul>
            </div>
            <div className="service-card reveal">
              <span className="service-icon"><Zap size={28} /></span>
              <h3>Vibe Code &rarr; Production</h3>
              <p>You built a prototype with AI tools. We refactor, harden, and ship it as real production software.</p>
              <ul className="service-list">
                <li>Code audit &amp; architecture cleanup</li>
                <li>Auth, security &amp; error handling</li>
                <li>Testing, CI/CD &amp; monitoring</li>
                <li>Works with any AI-generated codebase</li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* TESTIMONIALS */}
      <section style={{ padding: "7rem 0" }} id="testimonials">
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">What Clients Say</div>
            <h2>Results, not promises.</h2>
            <p>The standard we hold ourselves to on every project.</p>
          </div>

          <div className="testi-grid">
            {[
              {
                quote:
                  "\u201CWe went from zero mobile presence to a fully live app in 5 weeks. The process was airtight — weekly demos kept us confident the whole way through.\u201D",
                initials: "SC",
                name: "Sarah Chen",
                role: "Owner, Chen HVAC Services",
                result: "+62% mobile revenue in 60 days",
              },
              {
                quote:
                  "\u201CEvery agency quoted 6 months and enterprise prices. Swiftly delivered in 6 weeks at a third of the cost. The app paid for itself in the first month through reduced churn alone.\u201D",
                initials: "MJ",
                name: "Marcus Johnson",
                role: "Operations Manager, Rapid Retail",
                result: "ROI achieved in 11 days",
              },
              {
                quote:
                  "\u201CI was skeptical about the 6-week claim. They delivered in 5 weeks 3 days. The source code handover was clean, documented, and our in-house dev picked it up immediately.\u201D",
                initials: "ER",
                name: "Elena Rodriguez",
                role: "CEO, Bright Electric Co.",
                result: "29% customer retention boost",
              },
            ].map((t) => (
              <div className="testi-card reveal" key={t.initials}>
                <Stars />
                <p className="testi-quote">{t.quote}</p>
                <div className="testi-author">
                  <div className="testi-avatar">{t.initials}</div>
                  <div>
                    <h4>{t.name}</h4>
                    <p>{t.role}</p>
                  </div>
                </div>
                <span className="testi-result">{t.result}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* TRUST / WHY US */}
      <section style={{ padding: "7rem 0", background: "var(--bg2)" }}>
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">Why Trust Us</div>
            <h2>
              We&apos;re new. Here&apos;s
              <br />
              the honest case.
            </h2>
            <p>
              We don&apos;t have 100 clients. We have full attention for yours.
            </p>
          </div>

          <div className="trust-grid">
            {[
              {
                num: "01",
                title: "We have skin in the game",
                desc: "Being new means your project is our reputation. We can't afford mediocre — every app we ship is our entire portfolio.",
              },
              {
                num: "02",
                title: "Launch guarantee, in writing",
                desc: "Your app will be live on both stores within 6 weeks of kickoff — or we work for free until it is. Written into every contract.",
              },
              {
                num: "03",
                title: "Full transparency, always",
                desc: "Weekly video demos, a live project dashboard, and direct access to your developer. No account managers filtering answers.",
              },
              {
                num: "04",
                title: "You own 100% of everything",
                desc: "Source code, design files, store accounts — all yours from day one. No lock-in, no recurring fees unless you want ongoing support.",
              },
            ].map((card) => (
              <div className="trust-card reveal" key={card.num}>
                <div className="trust-num">{card.num}</div>
                <div>
                  <h4>{card.title}</h4>
                  <p>{card.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* PRICING */}
      <section id="pricing" style={{ padding: "7rem 0" }}>
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">Transparent Pricing</div>
            <h2>
              Fixed prices.
              <br />
              No surprises.
            </h2>
            <p>All plans include the 6-week launch guarantee.</p>
          </div>

          <div className="pricing-cards">
            {/* Starter */}
            <div className="pricing-card reveal">
              <div className="pricing-tier">Starter</div>
              <div className="pricing-price">
                <sup>$</sup>8,500
              </div>
              <div className="pricing-note">
                One platform &middot; up to 8 screens
              </div>
              <div className="pricing-divider"></div>
              <ul className="pricing-features">
                <li className="yes">
                  <span className="chk">✓</span> iOS or Android
                </li>
                <li className="yes">
                  <span className="chk">✓</span> UI/UX design included
                </li>
                <li className="yes">
                  <span className="chk">✓</span> Store submission
                </li>
                <li className="yes">
                  <span className="chk">✓</span> 6-week delivery guarantee
                </li>
                <li className="yes">
                  <span className="chk">✓</span> 30-day post-launch support
                </li>
                <li>
                  <span style={{ color: "var(--muted)" }}>–</span> Backend /
                  admin panel
                </li>
              </ul>
              <button className="pricing-btn outline" onClick={openModal}>
                Get Started
              </button>
            </div>

            {/* Growth */}
            <div className="pricing-card featured reveal">
              <div className="featured-badge">Most Popular</div>
              <div className="pricing-tier">Growth</div>
              <div className="pricing-price">
                <sup>$</sup>14,900
              </div>
              <div className="pricing-note">
                Both platforms &middot; up to 15 screens
              </div>
              <div className="pricing-divider"></div>
              <ul className="pricing-features">
                <li className="yes">
                  <span className="chk">✓</span> iOS + Android (both)
                </li>
                <li className="yes">
                  <span className="chk">✓</span> UI/UX design included
                </li>
                <li className="yes">
                  <span className="chk">✓</span> Both store submissions
                </li>
                <li className="yes">
                  <span className="chk">✓</span> 6-week delivery guarantee
                </li>
                <li className="yes">
                  <span className="chk">✓</span> 60-day post-launch support
                </li>
                <li className="yes">
                  <span className="chk">✓</span> Basic backend + admin panel
                </li>
              </ul>
              <button className="pricing-btn primary" onClick={openModal}>
                Book Discovery Call
              </button>
            </div>

            {/* Scale */}
            <div className="pricing-card reveal">
              <div className="pricing-tier">Scale</div>
              <div className="pricing-price">Custom</div>
              <div className="pricing-note">
                Complex builds &middot; integrations
              </div>
              <div className="pricing-divider"></div>
              <ul className="pricing-features">
                <li className="yes">
                  <span className="chk">✓</span> iOS + Android (both)
                </li>
                <li className="yes">
                  <span className="chk">✓</span> Full custom UI/UX
                </li>
                <li className="yes">
                  <span className="chk">✓</span> Complex backend / API
                </li>
                <li className="yes">
                  <span className="chk">✓</span> Third-party integrations
                </li>
                <li className="yes">
                  <span className="chk">✓</span> 90-day post-launch support
                </li>
                <li className="yes">
                  <span className="chk">✓</span> Ongoing maintenance plan
                </li>
              </ul>
              <button className="pricing-btn outline" onClick={openModal}>
                Contact Sales
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section
        id="faq"
        style={{ padding: "7rem 0", background: "var(--bg2)" }}
      >
        <div className="container">
          <div className="section-header reveal">
            <div className="tag">FAQ</div>
            <h2>
              Questions we
              <br />
              always get asked.
            </h2>
          </div>

          <FAQ />
        </div>
      </section>

      {/* CTA BANNER */}
      <section id="book" className="cta-banner">
        <div className="container">
          <div className="cta-inner">
            <h2>
              Ready to see your app
              <br />
              <em>live in 6 weeks?</em>
            </h2>
            <div className="cta-right">
              <button className="btn-primary" onClick={openModal}>
                Book Your Free 30-Min Call &rarr;
              </button>
              <span className="cta-note">
                No commitment. No sales pitch. Just a conversation.
              </span>
            </div>
          </div>
        </div>
      </section>

      </main>

      {/* FOOTER */}
      <footer>
        <div className="container">
          <div className="footer-inner">
            <a href="#" className="footer-logo">
              <Image src="/logo.png" alt="Swiftly" width={30} height={30} />
              Swift<span>ly</span>
            </a>
            <div className="footer-links">
              <a href="#process">Process</a>
              <a href="#services">Services</a>
              <a href="#pricing">Pricing</a>
              <a href="#faq">FAQ</a>
              <a href="#book">Contact</a>
            </div>
            <span className="footer-copy">
              &copy; 2025 Swiftly. All rights reserved.
            </span>
          </div>
        </div>
      </footer>

      {/* CONTACT MODAL */}
      <ContactModal isOpen={modalOpen} onClose={closeModal} />
    </>
  );
}
